### ISSUE TITLE
create example with storing git state into Bee using fdp-storage

### ISSUE THREAD

**Issue by molekilla** [SurroundingArt64/beeson-git-schema#1]
Hi @SurroundingArt64 

Can you do a simple example demo where you upload, and download to fdp-storage, 

Thanks
Rogelio

**Comment by SurroundingArt64** [comment]
It shouldn't be different than any other `beeson` object. This is just a schema serialization-deserialization for fast verifiable proofs on the chain.

```js
const { swarmAddress, bytes } = beeSon.typeManager.superBeeSonAttributes()

const storage = Utils.createStorage()
storage.storageSaverSync(swarmAddress, bytes)
```
